### ISSUE TITLE
Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by hohl** [mistic100/angular-smilies#5]
just installed angular-smilies.min.js and the embed.min.css and the filter seems to work. However my log gets spammed with:

    TypeError: Cannot read property 'replace' of null
    at i (http://dev.alwyzon.com:9000/assets/javascripts/angular-smilies.min.js:6:844)

**Comment by mistic100** [comment]
could you test with the unminified version ? would be more useful

**Comment by hohl** [comment]
Thanks for the quick response. With build from latest commit:

```
TypeError: Cannot read property 'replace' of null
    at apply (http://localhost/assets/javascripts/angular-smilies.min.js:35:31)
    at fn (eval at <anonymous> (http://localhost/assets/lib/angularjs/angular.min.js:212:83), <anonymous>:4:466)
    at $get.c (http://localhost/assets/lib/angularjs/angular.min.js:117:424)
    at Object.$get.a.$watch.f (http://localhost/assets/lib/angularjs/angular.min.js:116:338)
    at n.$get.n.$digest (http://localhost/assets/lib/angularjs/angular.min.js:132:124)
    at n.$get.n.$apply (http://localhost/assets/lib/angularjs/angular.min.js:135:269)
    at l (http://localhost/assets/lib/angularjs/angular.min.js:87:152)
    at F (http://localhost/assets/lib/angularjs/angular.min.js:91:187)
    at XMLHttpRequest.K.onload (http://localhost/assets/lib/angularjs/angular.min.js:92:220)
```

**Comment by mistic100** [comment]
add `if (!input) return '';` on line 35
https://github.com/mistic100/angular-smilies/blob/master/dist/angular-smilies.js#L34

I didn't had this problem because I always init my model in my controller

**Comment by hohl** [comment]
that works

**Comment by mistic100** [comment]
Thank your for your debugging
